// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEc3x6btqSR9SiB83NDaKfAUiOM_6q_k',
    appId: '1:477540588403:web:bff0564809183330934306',
    messagingSenderId: '477540588403',
    projectId: 'proyecto-iot-9d46e',
    authDomain: 'proyecto-iot-9d46e.firebaseapp.com',
    databaseURL: 'https://proyecto-iot-9d46e-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-9d46e.firebasestorage.app',
    measurementId: 'G-GBLTNWCNX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-Vtyw3mByb6foGSn0Gnw-8GinsDlyP4',
    appId: '1:477540588403:android:cec41185f447b26b934306',
    messagingSenderId: '477540588403',
    projectId: 'proyecto-iot-9d46e',
    databaseURL: 'https://proyecto-iot-9d46e-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-9d46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxURWCGCuH0a384h5SevkL3BTYuihlGE',
    appId: '1:477540588403:ios:cabebd9849dac14b934306',
    messagingSenderId: '477540588403',
    projectId: 'proyecto-iot-9d46e',
    databaseURL: 'https://proyecto-iot-9d46e-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-9d46e.firebasestorage.app',
    iosBundleId: 'com.example.proyectoIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxURWCGCuH0a384h5SevkL3BTYuihlGE',
    appId: '1:477540588403:ios:cabebd9849dac14b934306',
    messagingSenderId: '477540588403',
    projectId: 'proyecto-iot-9d46e',
    databaseURL: 'https://proyecto-iot-9d46e-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-9d46e.firebasestorage.app',
    iosBundleId: 'com.example.proyectoIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEc3x6btqSR9SiB83NDaKfAUiOM_6q_k',
    appId: '1:477540588403:web:e6cc6e194d7a05f4934306',
    messagingSenderId: '477540588403',
    projectId: 'proyecto-iot-9d46e',
    authDomain: 'proyecto-iot-9d46e.firebaseapp.com',
    databaseURL: 'https://proyecto-iot-9d46e-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-iot-9d46e.firebasestorage.app',
    measurementId: 'G-KJB3QCSXN2',
  );
}
